name: WakaTime Stats

on:
  # Update daily at midnight (UTC)
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggers from the Actions tab
  workflow_dispatch:

permissions:
  contents: write  # needed to commit the updated README

jobs:
  update-waka-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README with WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
