name: Work Stats Readme

on:
  # Triggers manually
  workflow_dispatch:
  # Runs every 2 hours
  schedule:
    - cron: '0 */2 * * *'

# Make sure we can write changes to the repo
permissions:
  contents: write

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repo so we can update the README
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Run the athul/waka-readme action pinned to a stable version
      - name: Update README with Wakatime stats
        uses: athul/waka-readme@v1.2.6
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
